### ISSUE TITLE
Setting  a Background Image

### ISSUE THREAD

**Issue by setrar** [akveo/nebular#95]
Hi,

I am trying to set a background image to my layout (see below)

I added the below code to my `themes.scss` file but the background image only shows up in the user-created component `<app-header>`. 

It is not applying the background to any of the `<nb-layout-*>` components, nor the user-created `<app-footer>`

Is that the right way to do it?

Note: I also tried to play with positions, background-repeat, ...

`themes.scss`
```scss
// import Nebular Theme System and the default theme
@import '~@nebular/theme/styles/theming';
@import '~@nebular/theme/styles/themes/default';
@import '~@nebular/theme/styles/themes/cosmic';


%body {
  background-image: url('/assets/images/@auth/landing/landing_bg_web.png');
}

:host {
  @extend %body;
}

...<more code>

```
`layout-one-column.component.ts`
```html
    <nb-layout>
      <nb-layout-header fixed>
        <app-header></app-header>
      </nb-layout-header>

      <nb-sidebar class="menu-sidebar" tag="menu-sidebar" responsive>
        <ng-content select="nb-menu"></ng-content>
      </nb-sidebar>

      <nb-layout-column>
        <ng-content select="router-outlet"></ng-content>
      </nb-layout-column>

      <nb-layout-footer fixed>
        <app-footer></app-footer>
      </nb-layout-footer>
    </nb-layout>
```

**Comment by setrar** [comment]
got it working!

I followed the enabling theme documentation
https://akveo.github.io/nebular/#/docs/guides/enabling-theme-system

I wrote my `themes.scss` file with the image background variable `(i.e. url-bg)`

```SCSS
// import Nebular Theme System and the default theme
@import '~@nebular/theme/styles/theming';
@import '~@nebular/theme/styles/themes/default';

// and change some variables inside of the map
$nb-themes: nb-register-theme((

  url-bg: url('/assets/images/@auth/landing/landing_bg_web.png'),

  color-bg: gray,
  color-fg: white,
), default, default); // let's leave it as default
```

I then generated my layout component using Angular-CLI command

```bash
$ ng generate component @auth/components/LayoutNoSideBar --inline-template true --spec false
```

* populated the template field with the below content `(note: image-container)`

```Typescript
@Component({
  selector: 'app-layout-no-side-bar',
  template: `
    <nb-layout>
      <nb-layout-header fixed>
        <app-header></app-header>
      </nb-layout-header>

      <nb-layout-column class="image-container">
        <ng-content select="router-outlet"></ng-content>
      </nb-layout-column>

      <nb-layout-footer fixed>
        <app-footer></app-footer>
      </nb-layout-footer>
    </nb-layout>
  `,
  styleUrls: ['./layout-no-side-bar.component.scss']
})
export class LayoutNoSideBarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```
populated the `layout-no-side-bar.component.scss` with `nb-install-component`

```SCSS
@import '../../styles/themes';

@include nb-install-component() {

  .image-container {
    background-image: nb-theme(url-bg);
  }

}
```

but most IMPORTANTLY, angular-cli adds   encapsulation: `ViewEncapsulation.None` in the component `(i.e. @Component)`

Removing the `ViewEncapsulation.None` made the trick
